textures/trak5/glass
{
	qer_editorimage textures/trak5x/misc/misc_glass.tga
	surfaceparm trans
	cull disable
	qer_trans 0.5

	{
		map textures/trak5x/misc/misc_glass.tga
		blendfunc add
		//rgbGen vertex
		tcgen environment
		tcmod scale 4 4
	}	
}

// autogenerated to redirect
textures/trak5/wall1b
{
	{
		map textures/trak5x/wall/wall_wall1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim2b
{
	{
		map textures/trak5x/trim/trim_trim2b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall1d
{
	{
		map textures/trak5x/wall/wall_wall1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile5d
{
	{
		map textures/trak5x/floor/floor_tile5d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall2d
{
	{
		map textures/trak5x/wall/wall_wall2d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/crate1b
{
	{
		map textures/trak5x/panel/panel_crate1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel1e
{
	{
		map textures/trak5x/panel/panel_vertpanel1e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile2d
{
	{
		map textures/trak5x/floor/floor_tile2d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/crate1c
{
	{
		map textures/trak5x/panel/panel_crate1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile4e
{
	{
		map textures/trak5x/floor/floor_tile4e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trisec1b
{
	{
		map textures/trak5x/trim/trim_trisec1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim6a
{
	{
		map textures/trak5x/trim/trim_trim6a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/floor2e
{
	{
		map textures/trak5x/floor/floor_floor2e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/light2a
{
	{
		map textures/trak5x/light/light_light2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall5a
{
	{
		map textures/trak5x/wall/wall_wall5a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/floor2d
{
	{
		map textures/trak5x/floor/floor_floor2d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/graypanel2
{
	{
		map textures/trak5x/panel/panel_graypanel2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall3c
{
	{
		map textures/trak5x/wall/wall_wall3c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim5e
{
	{
		map textures/trak5x/trim/trim_trim5e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel1a
{
	{
		map textures/trak5x/panel/panel_vertpanel1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim9c
{
	{
		map textures/trak5x/trim/trim_trim9c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/comp1d
{
	{
		map textures/trak5x/panel/panel_comp1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall5c
{
	{
		map textures/trak5x/wall/wall_wall5c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall6a
{
	{
		map textures/trak5x/wall/wall_wall6a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/crate1d
{
	{
		map textures/trak5x/panel/panel_crate1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim6e
{
	{
		map textures/trak5x/trim/trim_trim6e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile2c
{
	{
		map textures/trak5x/floor/floor_tile2c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/pipe1a
{
	{
		map textures/trak5x/base/base_pipe1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/graypanel1
{
	{
		map textures/trak5x/panel/panel_graypanel1.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall2c
{
	{
		map textures/trak5x/wall/wall_wall2c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/ceil1a
{
	{
		map textures/trak5x/panel/panel_ceil1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile5c
{
	{
		map textures/trak5x/floor/floor_tile5c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall2b
{
	{
		map textures/trak5x/wall/wall_wall2b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/floor2c
{
	{
		map textures/trak5x/floor/floor_floor2c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile3d
{
	{
		map textures/trak5x/floor/floor_tile3d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim7e
{
	{
		map textures/trak5x/trim/trim_trim7e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall1a
{
	{
		map textures/trak5x/wall/wall_wall1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim8a
{
	{
		map textures/trak5x/trim/trim_trim8a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile1e
{
	{
		map textures/trak5x/floor/floor_tile1e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim8b
{
	{
		map textures/trak5x/trim/trim_trim8b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel2c
{
	{
		map textures/trak5x/panel/panel_vertpanel2c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/stair1a
{
	{
		map textures/trak5x/trim/trim_stair1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trisec1d
{
	{
		map textures/trak5x/panel/panel_trisec1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim6d
{
	{
		map textures/trak5x/trim/trim_trim6d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall5b
{
	{
		map textures/trak5x/wall/wall_wall5b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel2b
{
	{
		map textures/trak5x/panel/panel_vertpanel2b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile5a
{
	{
		map textures/trak5x/floor/floor_tile5a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile1a
{
	{
		map textures/trak5x/floor/floor_tile1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/crate1a
{
	{
		map textures/trak5x/panel/panel_crate1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall7a
{
	{
		map textures/trak5x/wall/wall_wall7a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim3c
{
	{
		map textures/trak5x/trim/trim_trim3c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel2e
{
	{
		map textures/trak5x/panel/panel_vertpanel2e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall2e
{
	{
		map textures/trak5x/wall/wall_wall2e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/light1a
{
	{
		map textures/trak5x/light/light_light1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim4b
{
	{
		map textures/trak5x/trim/trim_trim4b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim4c
{
	{
		map textures/trak5x/trim/trim_trim4c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim5c
{
	{
		map textures/trak5x/trim/trim_trim5c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile2b
{
	{
		map textures/trak5x/floor/floor_tile2b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/basictrim1a
{
	{
		map textures/trak5x/trim/trim_basictrim1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile1b
{
	{
		map textures/trak5x/floor/floor_tile1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall3a
{
	{
		map textures/trak5x/wall/wall_wall3a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/comp1b
{
	{
		map textures/trak5x/panel/panel_comp1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim2a
{
	{
		map textures/trak5x/trim/trim_trim2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/comp1e
{
	{
		map textures/trak5x/panel/panel_comp1e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/pipe1b
{
	{
		map textures/trak5x/base/base_pipe1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile4c
{
	{
		map textures/trak5x/floor/floor_tile4c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim3a
{
	{
		map textures/trak5x/trim/trim_trim3a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall3e
{
	{
		map textures/trak5x/wall/wall_wall3e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall3b
{
	{
		map textures/trak5x/wall/wall_wall3b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim6b
{
	{
		map textures/trak5x/trim/trim_trim6b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile3c
{
	{
		map textures/trak5x/floor/floor_tile3c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile3b
{
	{
		map textures/trak5x/floor/floor_tile3b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/comp1c
{
	{
		map textures/trak5x/panel/panel_comp1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim7a
{
	{
		map textures/trak5x/trim/trim_trim7a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/base1a
{
	{
		map textures/trak5x/base/base_base1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/holes1b
{
	{
		map textures/trak5x/base/base_holes1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile5e
{
	{
		map textures/trak5x/floor/floor_tile5e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trisec1a
{
	{
		map textures/trak5x/trim/trim_trisec1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile1c
{
	{
		map textures/trak5x/floor/floor_tile1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall5e
{
	{
		map textures/trak5x/wall/wall_wall5e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim3b
{
	{
		map textures/trak5x/trim/trim_trim3b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim5d
{
	{
		map textures/trak5x/trim/trim_trim5d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim8c
{
	{
		map textures/trak5x/trim/trim_trim8c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim9b
{
	{
		map textures/trak5x/trim/trim_trim9b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall4e
{
	{
		map textures/trak5x/wall/wall_wall4e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel2a
{
	{
		map textures/trak5x/panel/panel_vertpanel2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/pipez1a
{
	{
		map textures/trak5x/misc/misc_pipez1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim8d
{
	{
		map textures/trak5x/trim/trim_trim8d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim7c
{
	{
		map textures/trak5x/trim/trim_trim7c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim1b
{
	{
		map textures/trak5x/trim/trim_trim1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel2d
{
	{
		map textures/trak5x/panel/panel_vertpanel2d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim4e
{
	{
		map textures/trak5x/trim/trim_trim4e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall2a
{
	{
		map textures/trak5x/wall/wall_wall2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/basictrim1b
{
	{
		map textures/trak5x/trim/trim_basictrim1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim8e
{
	{
		map textures/trak5x/trim/trim_trim8e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile5b
{
	{
		map textures/trak5x/floor/floor_tile5b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall1c
{
	{
		map textures/trak5x/wall/wall_wall1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/pits1a
{
	{
		map textures/trak5x/base/base_pits1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/floor2a
{
	{
		map textures/trak5x/floor/floor_floor2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/base1b
{
	{
		map textures/trak5x/base/base_base1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel1d
{
	{
		map textures/trak5x/panel/panel_vertpanel1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim9a
{
	{
		map textures/trak5x/trim/trim_trim9a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile3e
{
	{
		map textures/trak5x/floor/floor_tile3e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trisec1c
{
	{
		map textures/trak5x/panel/panel_trisec1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim7b
{
	{
		map textures/trak5x/trim/trim_trim7b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/floor2f
{
	{
		map textures/trak5x/floor/floor_floor2f.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/base1c
{
	{
		map textures/trak5x/base/base_base1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim5a
{
	{
		map textures/trak5x/trim/trim_trim5a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim4a
{
	{
		map textures/trak5x/trim/trim_trim4a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim9d
{
	{
		map textures/trak5x/trim/trim_trim9d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/grate2a
{
	{
		map textures/trak5x/panel/panel_grate2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall4c
{
	{
		map textures/trak5x/wall/wall_wall4c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim6c
{
	{
		map textures/trak5x/trim/trim_trim6c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/graypanel3
{
	{
		map textures/trak5x/panel/panel_graypanel3.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/holes1a
{
	{
		map textures/trak5x/base/base_holes1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim3e
{
	{
		map textures/trak5x/trim/trim_trim3e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile4d
{
	{
		map textures/trak5x/floor/floor_tile4d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/floor2b
{
	{
		map textures/trak5x/floor/floor_floor2b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim4d
{
	{
		map textures/trak5x/trim/trim_trim4d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/pipe1c
{
	{
		map textures/trak5x/base/base_pipe1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel1c
{
	{
		map textures/trak5x/panel/panel_vertpanel1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/grate1a
{
	{
		map textures/trak5x/panel/panel_grate1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall4d
{
	{
		map textures/trak5x/wall/wall_wall4d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/ribs1a
{
	{
		map textures/trak5x/base/base_ribs1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim5b
{
	{
		map textures/trak5x/trim/trim_trim5b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile1d
{
	{
		map textures/trak5x/floor/floor_tile1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile4a
{
	{
		map textures/trak5x/floor/floor_tile4a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim3d
{
	{
		map textures/trak5x/trim/trim_trim3d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall5d
{
	{
		map textures/trak5x/wall/wall_wall5d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall4a
{
	{
		map textures/trak5x/wall/wall_wall4a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/comp1a
{
	{
		map textures/trak5x/panel/panel_comp1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile4b
{
	{
		map textures/trak5x/floor/floor_tile4b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim9e
{
	{
		map textures/trak5x/trim/trim_trim9e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall3d
{
	{
		map textures/trak5x/wall/wall_wall3d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall1e
{
	{
		map textures/trak5x/wall/wall_wall1e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile2a
{
	{
		map textures/trak5x/floor/floor_tile2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/wall4b
{
	{
		map textures/trak5x/wall/wall_wall4b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim1a
{
	{
		map textures/trak5x/trim/trim_trim1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/thingy1a
{
	{
		map textures/trak5x/misc/misc_thingy1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/panel1a
{
	{
		map textures/trak5x/panel/panel_panel1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/tile3a
{
	{
		map textures/trak5x/floor/floor_tile3a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/light3a
{
	{
		map textures/trak5x/light/light_light3a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/panel2a
{
	{
		map textures/trak5x/panel/panel_panel2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/trim7d
{
	{
		map textures/trak5x/trim/trim_trim7d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/pipe1d
{
	{
		map textures/trak5x/base/base_pipe1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/vertpanel1b
{
	{
		map textures/trak5x/panel/panel_vertpanel1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak5/crate1e
{
	{
		map textures/trak5x/panel/panel_crate1e.tga
	}
	{
		map $lightmap
	}
}
