textures/trak4/northwing
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_northwing.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_northwing.tga
		rgbGen identity
		blendfunc add
	}
}

textures/trak4/southwing
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_southwing.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_southwing.tga
		rgbGen identity
		blendfunc add
	}
}

textures/trak4/help
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_help.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_help.tga
		rgbGen identity
	}
}

textures/trak4/pills
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_pills.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_pills.tga
		rgbGen identity
		blendfunc add
	}
}

textures/trak4/theater1
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_theater1.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_theater1.tga
		rgbGen identity
		blendfunc add
	}
}

textures/trak4/theater2
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_theater2.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_theater2.tga
		rgbGen identity
		blendfunc add
	}
}

textures/trak4/exit
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_exit.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_exit.tga
		rgbGen identity
		blendfunc add
	}
}

textures/trak4/iso1
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_iso1.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_iso1.tga
		rgbGen identity
		blendfunc add
	}
}

textures/trak4/iso2
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_iso2.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_iso2.tga
		rgbGen identity
		blendfunc add
	}
}

textures/trak4/iso3
{
	cull none
	qer_editorimage textures/trak4x/decal/decal_iso3.tga
	qer_trans 0.6
	surfaceparm trans
	surfaceparm alphashadow
	surfaceparm nonsolid
	{
		map $lightmap
		alphaFunc GT0
		rgbGen identity
	}
	{
		map textures/trak4x/decal/decal_iso3.tga
		rgbGen identity
		blendfunc add
	}
}

// autogenerated to redirect
textures/trak4/plaster3d
{
	{
		map textures/trak4x/wall/wall_plaster3d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/brick2a
{
	{
		map textures/trak4x/wall/wall_brick2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3-2
{
	{
		map textures/trak4x/wall/wall_plaster3-2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/door1d
{
	{
		map textures/trak4x/wall/wall_door1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/door1c
{
	{
		map textures/trak4x/wall/wall_door1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/door1
{
	{
		map textures/trak4x/wall/wall_door1.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/paint_yellow
{
	{
		map textures/trak4x/base/base_paint_yellow.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/paint_red
{
	{
		map textures/trak4x/base/base_paint_red.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3c-2
{
	{
		map textures/trak4x/wall/wall_plaster3c-2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/paint_green
{
	{
		map textures/trak4x/base/base_paint_green.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/brick2b
{
	{
		map textures/trak4x/wall/wall_brick2b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3
{
	{
		map textures/trak4x/wall/wall_plaster3.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/painted2
{
	{
		map textures/trak4x/base/base_painted2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/door1b
{
	{
		map textures/trak4x/wall/wall_door1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete3
{
	{
		map textures/trak4x/base/base_concrete3.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/rust1a
{
	{
		map textures/trak4x/base/base_rust1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3c
{
	{
		map textures/trak4x/wall/wall_plaster3c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/tile2b
{
	{
		map textures/trak4x/floor/floor_tile2b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/paint_dblue
{
	{
		map textures/trak4x/base/base_paint_dblue.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/trim1
{
	{
		map textures/trak4x/trim/trim_trim1.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3b
{
	{
		map textures/trak4x/wall/wall_plaster3b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/paint_purp
{
	{
		map textures/trak4x/base/base_paint_purp.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/tile3c
{
	{
		map textures/trak4x/floor/floor_tile3c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/paperdecal
{
	{
		map textures/trak4x/decal/decal_paperdecal.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/tile3b
{
	{
		map textures/trak4x/floor/floor_tile3b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/trim1e
{
	{
		map textures/trak4x/trim/trim_trim1e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3b-2
{
	{
		map textures/trak4x/wall/wall_plaster3b-2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/grate1
{
	{
		map textures/trak4x/trim/trim_grate1.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3d-2
{
	{
		map textures/trak4x/wall/wall_plaster3d-2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/brick2
{
	{
		map textures/trak4x/wall/wall_brick2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/brick1
{
	{
		map textures/trak4x/wall/wall_brick1.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/paint_blue
{
	{
		map textures/trak4x/base/base_paint_blue.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/door
{
	{
		map textures/trak4x/decal/decal_door.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete6
{
	{
		map textures/trak4x/base/base_concrete6.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/trim1c
{
	{
		map textures/trak4x/trim/trim_trim1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/trim1d
{
	{
		map textures/trak4x/trim/trim_trim1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/door1e
{
	{
		map textures/trak4x/wall/wall_door1e.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/trim1b
{
	{
		map textures/trak4x/trim/trim_trim1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/rust2
{
	{
		map textures/trak4x/base/base_rust2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3a
{
	{
		map textures/trak4x/wall/wall_plaster3a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/rust1
{
	{
		map textures/trak4x/base/base_rust1.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete1a
{
	{
		map textures/trak4x/base/base_concrete1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/rust1b
{
	{
		map textures/trak4x/base/base_rust1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/rust2b
{
	{
		map textures/trak4x/base/base_rust2b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster1
{
	{
		map textures/trak4x/wall/wall_plaster1.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete5a
{
	{
		map textures/trak4x/base/base_concrete5a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/trim1f
{
	{
		map textures/trak4x/trim/trim_trim1f.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/tile1
{
	{
		map textures/trak4x/floor/floor_tile1.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/grate2a
{
	{
		map textures/trak4x/trim/trim_grate2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete2a
{
	{
		map textures/trak4x/base/base_concrete2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3a-3
{
	{
		map textures/trak4x/wall/wall_plaster3a-3.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/door1a
{
	{
		map textures/trak4x/wall/wall_door1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3c-3
{
	{
		map textures/trak4x/wall/wall_plaster3c-3.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete4a
{
	{
		map textures/trak4x/base/base_concrete4a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/wood1d
{
	{
		map textures/trak4x/base/wood1d.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/tile2a
{
	{
		map textures/trak4x/floor/floor_tile2a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete5b
{
	{
		map textures/trak4x/base/base_concrete5b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/trim1a
{
	{
		map textures/trak4x/trim/trim_trim1a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/plaster3a-2
{
	{
		map textures/trak4x/wall/wall_plaster3a-2.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/tile3a
{
	{
		map textures/trak4x/floor/floor_tile3a.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete1b
{
	{
		map textures/trak4x/base/base_concrete1b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/wallpainting
{
	{
		map textures/trak4x/decal/decal_wallpainting.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/paint_pink
{
	{
		map textures/trak4x/base/base_paint_pink.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/concrete4b
{
	{
		map textures/trak4x/base/base_concrete4b.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/rust1c
{
	{
		map textures/trak4x/base/base_rust1c.tga
	}
	{
		map $lightmap
	}
}

// autogenerated to redirect
textures/trak4/wood1c
{
	{
		map textures/trak4x/base/wood1c.tga
	}
	{
		map $lightmap
	}
}
